import { describe, expect, test } from "vitest";

import { buildMarketingReportingSummary } from "./marketing-reporting";

const REFERRAL_TOKEN_KEY = "token";

describe("marketing reporting summary", () => {
  test("aggregates attribution, activation milestones, and referral lifecycle counts", () => {
    const summary = buildMarketingReportingSummary({
      leads: [
        {
          id: "lead-1",
          email: "parent@families.hk",
          fullName: "Parent Example",
          childStageInterest: "MYP",
          source: "ib-parent-starter-kit",
          pagePath: "/ib-parent-starter-kit",
          referrerUrl: null,
          utmSource: "google",
          utmMedium: "organic",
          utmCampaign: null,
          utmContent: null,
          utmTerm: null,
          captureCount: 1,
          deliveryStatus: "sent",
          deliveryMessageId: "lead-message-1",
          deliveryErrorMessage: null,
          deliveredAt: "2026-04-10T00:00:00.000Z",
          nurtureEmailCount: 2,
          nurtureLastAttemptAt: "2026-04-14T00:00:00.000Z",
          nurtureLastSentAt: "2026-04-14T00:00:00.000Z",
          nurtureLastStage: 2,
          nurtureLastStatus: "sent",
          nurtureLastMessageId: "nurture-message-2",
          nurtureLastError: null,
          createdAt: "2026-04-10T00:00:00.000Z",
          updatedAt: "2026-04-14T00:00:00.000Z",
        },
        {
          id: "lead-2",
          email: "lead-two@families.hk",
          fullName: "Lead Two",
          childStageInterest: "DP",
          source: "ib-parent-starter-kit",
          pagePath: "/ib-parent-starter-kit",
          referrerUrl: null,
          utmSource: "newsletter",
          utmMedium: "email",
          utmCampaign: "april-parents",
          utmContent: null,
          utmTerm: null,
          captureCount: 1,
          deliveryStatus: "failed",
          deliveryMessageId: null,
          deliveryErrorMessage: "SMTP offline",
          deliveredAt: null,
          nurtureEmailCount: 1,
          nurtureLastAttemptAt: "2026-04-15T00:00:00.000Z",
          nurtureLastSentAt: null,
          nurtureLastStage: 1,
          nurtureLastStatus: "failed",
          nurtureLastMessageId: null,
          nurtureLastError: "SMTP offline",
          createdAt: "2026-04-11T00:00:00.000Z",
          updatedAt: "2026-04-15T00:00:00.000Z",
        },
      ],
      referralInvites: [
        {
          id: "invite-1",
          [REFERRAL_TOKEN_KEY]: "referral-code-1",
          referrerParentId: "parent-1",
          referrerParentEmail: "parent@families.hk",
          referrerParentFullName: "Parent Example",
          inviteeEmail: "friend@families.hk",
          inviteeFullName: "Friend Example",
          inviteeStageInterest: "DP",
          sourcePath: "/dashboard",
          deliveryStatus: "sent",
          deliveryMessageId: "invite-message-1",
          deliveryErrorMessage: null,
          sentAt: "2026-04-10T01:00:00.000Z",
          acceptedAt: "2026-04-10T02:00:00.000Z",
          trialStartedAt: "2026-04-10T03:00:00.000Z",
          inviteeParentId: "parent-2",
          createdAt: "2026-04-10T01:00:00.000Z",
          updatedAt: "2026-04-10T03:00:00.000Z",
        },
      ],
      profiles: [
        {
          parent: {
            id: "parent-1",
            email: "parent@families.hk",
            fullName: "Parent Example",
            countryCode: "HK",
            deliveryTimeZone: "Asia/Hong_Kong",
            preferredDeliveryLocalTime: "09:00",
            firstAuthenticatedAt: "2026-04-10T00:00:00.000Z",
            childProfileCompletedAt: "2026-04-10T00:05:00.000Z",
            firstDispatchableChannelAt: "2026-04-10T00:10:00.000Z",
            firstBriefDeliveredAt: "2026-04-10T00:20:00.000Z",
            firstPaidAt: null,
            onboardingReminderCount: 0,
            onboardingReminderLastAttemptAt: null,
            onboardingReminderLastSentAt: null,
            onboardingReminderLastStage: null,
            onboardingReminderLastStatus: null,
            onboardingReminderLastMessageId: null,
            onboardingReminderLastError: null,
            subscriptionStatus: "trial",
            subscriptionPlan: "monthly",
            stripeCustomerId: null,
            stripeSubscriptionId: null,
            trialStartedAt: "2026-04-10T00:00:00.000Z",
            trialEndsAt: "2026-04-17T00:00:00.000Z",
            subscriptionActivatedAt: null,
            subscriptionRenewalAt: null,
            latestInvoiceId: null,
            latestInvoiceNumber: null,
            latestInvoiceStatus: null,
            latestInvoiceHostedUrl: null,
            latestInvoicePdfUrl: null,
            latestInvoiceAmountPaid: null,
            latestInvoiceCurrency: null,
            latestInvoicePaidAt: null,
            latestInvoicePeriodStart: null,
            latestInvoicePeriodEnd: null,
            notionWorkspaceId: null,
            notionWorkspaceName: null,
            notionBotId: null,
            notionDatabaseId: null,
            notionDatabaseName: null,
            notionDataSourceId: null,
            notionAuthorizedAt: null,
            notionLastSyncedAt: null,
            notionLastSyncStatus: null,
            notionLastSyncMessage: null,
            notionLastSyncPageId: null,
            notionLastSyncPageUrl: null,
            createdAt: "2026-04-10T00:00:00.000Z",
            updatedAt: "2026-04-10T00:20:00.000Z",
          },
          student: {
            id: "student-1",
            parentId: "parent-1",
            studentName: "Katherine",
            programme: "MYP",
            programmeYear: 3,
            interestTags: [],
            goodnotesEmail: "katherine@goodnotes.email",
            goodnotesConnected: true,
            goodnotesVerifiedAt: "2026-04-10T00:10:00.000Z",
            goodnotesLastTestSentAt: null,
            goodnotesLastDeliveryStatus: "success",
            goodnotesLastDeliveryMessage: "Ready.",
            notionConnected: false,
            createdAt: "2026-04-10T00:00:00.000Z",
            updatedAt: "2026-04-10T00:20:00.000Z",
          },
        },
        {
          parent: {
            id: "parent-2",
            email: "friend@families.hk",
            fullName: "Friend Example",
            countryCode: "HK",
            deliveryTimeZone: "Asia/Hong_Kong",
            preferredDeliveryLocalTime: "09:00",
            firstAuthenticatedAt: "2026-04-10T02:30:00.000Z",
            childProfileCompletedAt: "2026-04-10T02:35:00.000Z",
            firstDispatchableChannelAt: "2026-04-10T02:40:00.000Z",
            firstBriefDeliveredAt: "2026-04-10T03:30:00.000Z",
            firstPaidAt: "2026-04-12T00:00:00.000Z",
            onboardingReminderCount: 0,
            onboardingReminderLastAttemptAt: null,
            onboardingReminderLastSentAt: null,
            onboardingReminderLastStage: null,
            onboardingReminderLastStatus: null,
            onboardingReminderLastMessageId: null,
            onboardingReminderLastError: null,
            subscriptionStatus: "active",
            subscriptionPlan: "yearly",
            stripeCustomerId: "cus_123",
            stripeSubscriptionId: "sub_123",
            trialStartedAt: "2026-04-10T02:30:00.000Z",
            trialEndsAt: "2026-04-17T02:30:00.000Z",
            subscriptionActivatedAt: "2026-04-12T00:00:00.000Z",
            subscriptionRenewalAt: "2027-04-12T00:00:00.000Z",
            latestInvoiceId: "in_123",
            latestInvoiceNumber: "123",
            latestInvoiceStatus: "paid",
            latestInvoiceHostedUrl: null,
            latestInvoicePdfUrl: null,
            latestInvoiceAmountPaid: 12900,
            latestInvoiceCurrency: "usd",
            latestInvoicePaidAt: "2026-04-12T00:00:00.000Z",
            latestInvoicePeriodStart: "2026-04-12T00:00:00.000Z",
            latestInvoicePeriodEnd: "2027-04-12T00:00:00.000Z",
            notionWorkspaceId: null,
            notionWorkspaceName: null,
            notionBotId: null,
            notionDatabaseId: null,
            notionDatabaseName: null,
            notionDataSourceId: null,
            notionAuthorizedAt: null,
            notionLastSyncedAt: null,
            notionLastSyncStatus: null,
            notionLastSyncMessage: null,
            notionLastSyncPageId: null,
            notionLastSyncPageUrl: null,
            createdAt: "2026-04-10T02:30:00.000Z",
            updatedAt: "2026-04-12T00:00:00.000Z",
          },
          student: {
            id: "student-2",
            parentId: "parent-2",
            studentName: "Theo",
            programme: "DP",
            programmeYear: 1,
            interestTags: [],
            goodnotesEmail: "theo@goodnotes.email",
            goodnotesConnected: true,
            goodnotesVerifiedAt: "2026-04-10T02:40:00.000Z",
            goodnotesLastTestSentAt: null,
            goodnotesLastDeliveryStatus: "success",
            goodnotesLastDeliveryMessage: "Ready.",
            notionConnected: true,
            createdAt: "2026-04-10T02:30:00.000Z",
            updatedAt: "2026-04-12T00:00:00.000Z",
          },
        },
        {
          parent: {
            id: "parent-3",
            email: "direct@families.hk",
            fullName: "Direct Example",
            countryCode: "HK",
            deliveryTimeZone: "Asia/Hong_Kong",
            preferredDeliveryLocalTime: "09:00",
            firstAuthenticatedAt: "2026-04-11T00:00:00.000Z",
            childProfileCompletedAt: "2026-04-11T00:05:00.000Z",
            firstDispatchableChannelAt: "2026-04-11T00:10:00.000Z",
            firstBriefDeliveredAt: null,
            firstPaidAt: null,
            onboardingReminderCount: 0,
            onboardingReminderLastAttemptAt: null,
            onboardingReminderLastSentAt: null,
            onboardingReminderLastStage: null,
            onboardingReminderLastStatus: null,
            onboardingReminderLastMessageId: null,
            onboardingReminderLastError: null,
            subscriptionStatus: "trial",
            subscriptionPlan: "monthly",
            stripeCustomerId: null,
            stripeSubscriptionId: null,
            trialStartedAt: "2026-04-11T00:00:00.000Z",
            trialEndsAt: "2026-04-18T00:00:00.000Z",
            subscriptionActivatedAt: null,
            subscriptionRenewalAt: null,
            latestInvoiceId: null,
            latestInvoiceNumber: null,
            latestInvoiceStatus: null,
            latestInvoiceHostedUrl: null,
            latestInvoicePdfUrl: null,
            latestInvoiceAmountPaid: null,
            latestInvoiceCurrency: null,
            latestInvoicePaidAt: null,
            latestInvoicePeriodStart: null,
            latestInvoicePeriodEnd: null,
            notionWorkspaceId: null,
            notionWorkspaceName: null,
            notionBotId: null,
            notionDatabaseId: null,
            notionDatabaseName: null,
            notionDataSourceId: null,
            notionAuthorizedAt: null,
            notionLastSyncedAt: null,
            notionLastSyncStatus: null,
            notionLastSyncMessage: null,
            notionLastSyncPageId: null,
            notionLastSyncPageUrl: null,
            createdAt: "2026-04-11T00:00:00.000Z",
            updatedAt: "2026-04-11T00:10:00.000Z",
          },
          student: {
            id: "student-3",
            parentId: "parent-3",
            studentName: "Mina",
            programme: "MYP",
            programmeYear: 4,
            interestTags: [],
            goodnotesEmail: "",
            goodnotesConnected: false,
            goodnotesVerifiedAt: null,
            goodnotesLastTestSentAt: null,
            goodnotesLastDeliveryStatus: null,
            goodnotesLastDeliveryMessage: null,
            notionConnected: false,
            createdAt: "2026-04-11T00:00:00.000Z",
            updatedAt: "2026-04-11T00:10:00.000Z",
          },
        },
      ],
      notebookEntries: [
        {
          id: "entry-1",
          parentId: "parent-1",
          parentEmail: "parent@families.hk",
          studentId: "student-1",
          programme: "MYP",
          entryType: "inquiry-notebook",
          entryOrigin: "system",
          title: "Inquiry",
          body: "Body",
          knowledgeBankTitle: "KB",
          sourceBriefId: "brief-1",
          sourceScheduledFor: "2026-04-10",
          sourceHeadline: "Headline",
          topicTags: [],
          interestTags: [],
          savedSource: "dashboard",
          savedAt: "2026-04-10T00:30:00.000Z",
          createdAt: "2026-04-10T00:30:00.000Z",
          updatedAt: "2026-04-10T00:30:00.000Z",
        },
        {
          id: "entry-2",
          parentId: "parent-1",
          parentEmail: "parent@families.hk",
          studentId: "student-1",
          programme: "MYP",
          entryType: "global-context-note",
          entryOrigin: "authored",
          title: "Global context",
          body: "Body",
          knowledgeBankTitle: "KB",
          sourceBriefId: "brief-1",
          sourceScheduledFor: "2026-04-10",
          sourceHeadline: "Headline",
          topicTags: [],
          interestTags: [],
          savedSource: "reflection",
          savedAt: "2026-04-10T00:40:00.000Z",
          createdAt: "2026-04-10T00:40:00.000Z",
          updatedAt: "2026-04-10T00:40:00.000Z",
        },
      ],
      weeklyRecaps: [
        {
          id: "recap-1",
          parentId: "parent-2",
          parentEmail: "friend@families.hk",
          studentId: "student-2",
          programme: "DP",
          weekKey: "2026-W15",
          weekLabel: "Apr 6-12, 2026",
          summary: "Summary",
          focusTags: ["TOK"],
          entryMix: [],
          retrievalPrompts: [],
          retrievalResponses: [],
          generationSource: "scheduled",
          notionLastSyncedAt: null,
          notionLastSyncPageId: null,
          notionLastSyncPageUrl: null,
          emailLastSentAt: null,
          emailLastStatus: null,
          emailLastMessageId: null,
          emailLastErrorMessage: null,
          createdAt: "2026-04-12T00:00:00.000Z",
          updatedAt: "2026-04-12T00:00:00.000Z",
        },
      ],
    });

    expect(summary.leads.total).toBe(2);
    expect(summary.leads.delivered).toBe(1);
    expect(summary.leads.nurtureSent).toBe(1);
    expect(summary.leads.nurtureFailed).toBe(1);
    expect(summary.activation.trialStarted).toBe(3);
    expect(summary.activation.firstBriefDelivered).toBe(2);
    expect(summary.activation.paidActivated).toBe(1);
    expect(summary.activation.notebookEntries).toBe(2);
    expect(summary.activation.weeklyRecaps).toBe(1);
    expect(summary.referrals.sent).toBe(1);
    expect(summary.referrals.accepted).toBe(1);
    expect(summary.referrals.trialStarted).toBe(1);
    expect(summary.attribution).toEqual([
      {
        source: "starter-kit",
        label: "Starter kit",
        profileCount: 1,
        trialStarted: 1,
        firstBriefDelivered: 1,
        paidActivated: 0,
      },
      {
        source: "referral",
        label: "Referral",
        profileCount: 1,
        trialStarted: 1,
        firstBriefDelivered: 1,
        paidActivated: 1,
      },
      {
        source: "direct",
        label: "Direct",
        profileCount: 1,
        trialStarted: 1,
        firstBriefDelivered: 0,
        paidActivated: 0,
      },
    ]);
    expect(summary.recentTrialProfiles[0]).toEqual(
      expect.objectContaining({
        parentEmail: "friend@families.hk",
        source: "referral",
        paidActivatedAt: "2026-04-12T00:00:00.000Z",
      }),
    );
  });

  test("excludes internal and test accounts from the reporting baseline", () => {
    const summary = buildMarketingReportingSummary({
      leads: [
        {
          id: "lead-internal",
          email: "admin@geledtech.com",
          fullName: "Internal Admin",
          childStageInterest: "MYP",
          source: "ib-parent-starter-kit",
          pagePath: "/ib-parent-starter-kit",
          referrerUrl: null,
          utmSource: "manual",
          utmMedium: "internal",
          utmCampaign: null,
          utmContent: null,
          utmTerm: null,
          captureCount: 1,
          deliveryStatus: "sent",
          deliveryMessageId: "internal-message",
          deliveryErrorMessage: null,
          deliveredAt: "2026-04-10T00:00:00.000Z",
          nurtureEmailCount: 1,
          nurtureLastAttemptAt: "2026-04-10T00:00:00.000Z",
          nurtureLastSentAt: "2026-04-10T00:00:00.000Z",
          nurtureLastStage: 1,
          nurtureLastStatus: "sent",
          nurtureLastMessageId: "internal-nurture",
          nurtureLastError: null,
          createdAt: "2026-04-10T00:00:00.000Z",
          updatedAt: "2026-04-10T00:00:00.000Z",
        },
        {
          id: "lead-qa",
          email: "piaccte+dailysparks-acq-qa-20260410@gmail.com",
          fullName: "Starter Kit QA",
          childStageInterest: "DP",
          source: "ib-parent-starter-kit",
          pagePath: "/ib-parent-starter-kit",
          referrerUrl: null,
          utmSource: "qa",
          utmMedium: "manual",
          utmCampaign: "starter-kit-acquisition-qa-2026-04-10",
          utmContent: "codex",
          utmTerm: "parent-reading",
          captureCount: 1,
          deliveryStatus: "sent",
          deliveryMessageId: "qa-message",
          deliveryErrorMessage: null,
          deliveredAt: "2026-04-10T00:00:00.000Z",
          nurtureEmailCount: 1,
          nurtureLastAttemptAt: "2026-04-10T00:00:00.000Z",
          nurtureLastSentAt: "2026-04-10T00:00:00.000Z",
          nurtureLastStage: 1,
          nurtureLastStatus: "sent",
          nurtureLastMessageId: "qa-nurture",
          nurtureLastError: null,
          createdAt: "2026-04-10T00:00:00.000Z",
          updatedAt: "2026-04-10T00:00:00.000Z",
        },
        {
          id: "lead-external",
          email: "parent@families.hk",
          fullName: "Parent Example",
          childStageInterest: "DP",
          source: "ib-parent-starter-kit",
          pagePath: "/ib-parent-starter-kit",
          referrerUrl: null,
          utmSource: "google",
          utmMedium: "organic",
          utmCampaign: null,
          utmContent: null,
          utmTerm: null,
          captureCount: 1,
          deliveryStatus: "sent",
          deliveryMessageId: "external-message",
          deliveryErrorMessage: null,
          deliveredAt: "2026-04-10T00:00:00.000Z",
          nurtureEmailCount: 1,
          nurtureLastAttemptAt: "2026-04-10T00:00:00.000Z",
          nurtureLastSentAt: "2026-04-10T00:00:00.000Z",
          nurtureLastStage: 1,
          nurtureLastStatus: "sent",
          nurtureLastMessageId: "external-nurture",
          nurtureLastError: null,
          createdAt: "2026-04-10T00:00:00.000Z",
          updatedAt: "2026-04-10T00:00:00.000Z",
        },
      ],
      referralInvites: [
        {
          id: "invite-internal",
          [REFERRAL_TOKEN_KEY]: "referral-code-internal",
          referrerParentId: "parent-internal",
          referrerParentEmail: "admin@geledtech.com",
          referrerParentFullName: "Internal Admin",
          inviteeEmail: "friend@families.hk",
          inviteeFullName: "Friend Example",
          inviteeStageInterest: "DP",
          sourcePath: "/dashboard",
          deliveryStatus: "sent",
          deliveryMessageId: "invite-message",
          deliveryErrorMessage: null,
          sentAt: "2026-04-10T00:00:00.000Z",
          acceptedAt: null,
          trialStartedAt: null,
          inviteeParentId: null,
          createdAt: "2026-04-10T00:00:00.000Z",
          updatedAt: "2026-04-10T00:00:00.000Z",
        },
      ],
      profiles: [
        {
          parent: {
            id: "parent-internal",
            email: "admin@geledtech.com",
            fullName: "Internal Admin",
            trialStartedAt: "2026-04-10T00:00:00.000Z",
            firstBriefDeliveredAt: "2026-04-10T01:00:00.000Z",
            firstPaidAt: "2026-04-10T02:00:00.000Z",
            subscriptionActivatedAt: "2026-04-10T02:00:00.000Z",
            trialConversionNurtureLastStage: 1,
            trialConversionNurtureLastStatus: "sent",
            updatedAt: "2026-04-10T02:00:00.000Z",
          },
          student: {
            studentName: "Internal Student",
            programme: "DP",
          },
        },
        {
          parent: {
            id: "parent-qa",
            email: "piaccte+dailysparks-acq-qa-20260410@gmail.com",
            fullName: "Starter Kit QA",
            trialStartedAt: "2026-04-10T00:00:00.000Z",
            firstBriefDeliveredAt: null,
            firstPaidAt: null,
            subscriptionActivatedAt: null,
            trialConversionNurtureLastStage: null,
            trialConversionNurtureLastStatus: null,
            updatedAt: "2026-04-10T00:00:00.000Z",
          },
          student: {
            studentName: "QA Student",
            programme: "DP",
          },
        },
        {
          parent: {
            id: "parent-external",
            email: "parent@families.hk",
            fullName: "Parent Example",
            trialStartedAt: "2026-04-10T00:00:00.000Z",
            firstBriefDeliveredAt: "2026-04-10T01:00:00.000Z",
            firstPaidAt: null,
            subscriptionActivatedAt: null,
            trialConversionNurtureLastStage: null,
            trialConversionNurtureLastStatus: null,
            updatedAt: "2026-04-10T01:00:00.000Z",
          },
          student: {
            studentName: "Theo",
            programme: "DP",
          },
        },
      ] as never[],
      notebookEntries: [
        {
          id: "entry-internal",
          parentId: "parent-internal",
          parentEmail: "admin@geledtech.com",
        },
        {
          id: "entry-qa",
          parentId: "parent-qa",
          parentEmail: "piaccte+dailysparks-acq-qa-20260410@gmail.com",
        },
        {
          id: "entry-external",
          parentId: "parent-external",
          parentEmail: "parent@families.hk",
        },
      ] as never[],
      weeklyRecaps: [
        {
          id: "recap-internal",
          parentId: "parent-internal",
          parentEmail: "admin@geledtech.com",
        },
        {
          id: "recap-qa",
          parentId: "parent-qa",
          parentEmail: "piaccte+dailysparks-acq-qa-20260410@gmail.com",
        },
        {
          id: "recap-external",
          parentId: "parent-external",
          parentEmail: "parent@families.hk",
        },
      ] as never[],
    });

    expect(summary.exclusions).toEqual({
      profiles: 2,
      leads: 2,
      referralInvites: 1,
      notebookEntries: 2,
      weeklyRecaps: 2,
    });
    expect(summary.leads.total).toBe(1);
    expect(summary.referrals.sent).toBe(0);
    expect(summary.activation.trialStarted).toBe(1);
    expect(summary.activation.firstBriefDelivered).toBe(1);
    expect(summary.activation.paidActivated).toBe(0);
    expect(summary.activation.notebookEntries).toBe(1);
    expect(summary.activation.weeklyRecaps).toBe(1);
    expect(summary.attribution).toEqual([
      {
        source: "starter-kit",
        label: "Starter kit",
        profileCount: 1,
        trialStarted: 1,
        firstBriefDelivered: 1,
        paidActivated: 0,
      },
      {
        source: "referral",
        label: "Referral",
        profileCount: 0,
        trialStarted: 0,
        firstBriefDelivered: 0,
        paidActivated: 0,
      },
      {
        source: "direct",
        label: "Direct",
        profileCount: 0,
        trialStarted: 0,
        firstBriefDelivered: 0,
        paidActivated: 0,
      },
    ]);
    expect(summary.recentLeads).toEqual([
      expect.objectContaining({
        email: "parent@families.hk",
      }),
    ]);
    expect(summary.recentTrialProfiles).toEqual([
      expect.objectContaining({
        parentEmail: "parent@families.hk",
      }),
    ]);
  });

  test("keeps direct families direct when a starter kit lead is captured only after trial start", () => {
    const summary = buildMarketingReportingSummary({
      leads: [
        {
          id: "late-lead",
          email: "direct@families.hk",
          fullName: "Direct Example",
          childStageInterest: "DP",
          source: "ib-parent-starter-kit",
          pagePath: "/ib-parent-starter-kit",
          referrerUrl: null,
          utmSource: "google",
          utmMedium: "organic",
          utmCampaign: null,
          utmContent: null,
          utmTerm: null,
          captureCount: 1,
          deliveryStatus: "sent",
          deliveryMessageId: "late-lead-message",
          deliveryErrorMessage: null,
          deliveredAt: "2026-04-12T00:00:00.000Z",
          nurtureEmailCount: 0,
          nurtureLastAttemptAt: null,
          nurtureLastSentAt: null,
          nurtureLastStage: null,
          nurtureLastStatus: null,
          nurtureLastMessageId: null,
          nurtureLastError: null,
          createdAt: "2026-04-12T00:00:00.000Z",
          updatedAt: "2026-04-12T00:00:00.000Z",
        },
      ],
      referralInvites: [],
      profiles: [
        {
          parent: {
            id: "parent-direct",
            email: "direct@families.hk",
            fullName: "Direct Example",
            trialStartedAt: "2026-04-10T00:00:00.000Z",
            firstAuthenticatedAt: "2026-04-10T00:00:00.000Z",
            firstBriefDeliveredAt: null,
            firstPaidAt: null,
            subscriptionActivatedAt: null,
            trialConversionNurtureLastStage: null,
            trialConversionNurtureLastStatus: null,
            createdAt: "2026-04-10T00:00:00.000Z",
            updatedAt: "2026-04-12T00:00:00.000Z",
          },
          student: {
            studentName: "Theo",
            programme: "DP",
          },
        },
      ] as never[],
      notebookEntries: [],
      weeklyRecaps: [],
    });

    expect(
      summary.attribution.find((entry) => entry.source === "direct")?.profileCount,
    ).toBe(1);
    expect(
      summary.attribution.find((entry) => entry.source === "starter-kit")
        ?.profileCount,
    ).toBe(0);
  });

  test("does not classify unaccepted referral invites as referral attribution", () => {
    const summary = buildMarketingReportingSummary({
      leads: [],
      referralInvites: [
        {
          id: "invite-1",
          [REFERRAL_TOKEN_KEY]: "unaccepted-referral",
          referrerParentId: "parent-1",
          referrerParentEmail: "referrer@families.hk",
          referrerParentFullName: "Referrer Parent",
          inviteeEmail: "friend@families.hk",
          inviteeFullName: "Friend Example",
          inviteeStageInterest: "DP",
          sourcePath: "/dashboard",
          deliveryStatus: "sent",
          deliveryMessageId: "invite-message",
          deliveryErrorMessage: null,
          sentAt: "2026-04-10T01:00:00.000Z",
          acceptedAt: null,
          trialStartedAt: null,
          inviteeParentId: null,
          createdAt: "2026-04-10T01:00:00.000Z",
          updatedAt: "2026-04-10T01:00:00.000Z",
        },
      ],
      profiles: [
        {
          parent: {
            id: "parent-2",
            email: "friend@families.hk",
            fullName: "Friend Example",
            trialStartedAt: "2026-04-10T02:30:00.000Z",
            firstAuthenticatedAt: "2026-04-10T02:30:00.000Z",
            firstBriefDeliveredAt: null,
            firstPaidAt: null,
            subscriptionActivatedAt: null,
            trialConversionNurtureLastStage: null,
            trialConversionNurtureLastStatus: null,
            createdAt: "2026-04-10T02:30:00.000Z",
            updatedAt: "2026-04-10T02:30:00.000Z",
          },
          student: {
            studentName: "Friend Example",
            programme: "DP",
          },
        },
      ] as never[],
      notebookEntries: [],
      weeklyRecaps: [],
    });

    expect(
      summary.attribution.find((entry) => entry.source === "referral")
        ?.profileCount,
    ).toBe(0);
    expect(
      summary.attribution.find((entry) => entry.source === "direct")?.profileCount,
    ).toBe(1);
  });
});
