#!/usr/bin/env bash
set -euo pipefail

PROJECT_ID="${GOOGLE_CLOUD_PROJECT:-gen-lang-client-0586185740}"
SERVICE_NAME="${SERVICE_NAME:-dailysparks-web}"
REGION="${REGION:-asia-east2}"
REPOSITORY="${REPOSITORY:-cloud-run-source-deploy}"
IMAGE="${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${SERVICE_NAME}:$(git rev-parse --short HEAD)"
ENV_VARS="NODE_ENV=production,DAILY_SPARKS_STORE_BACKEND=firestore,FIREBASE_PROJECT_ID=${PROJECT_ID}"
NOTION_OAUTH_CLIENT_ID_VALUE="${NOTION_OAUTH_CLIENT_ID:-335d872b-594c-8127-8bae-0037c94dabc3}"
NOTION_OAUTH_REDIRECT_URI_VALUE="${NOTION_OAUTH_REDIRECT_URI:-https://dailysparks.geledtech.com/api/notion/callback}"
GOODNOTES_FROM_EMAIL_VALUE="${GOODNOTES_FROM_EMAIL:-info@geledtech.com}"
GOODNOTES_FROM_NAME_VALUE="${GOODNOTES_FROM_NAME:-Growth Education Limited}"
CURRENT_SERVICE_CONFIG_JSON="$(gcloud run services describe "${SERVICE_NAME}" --region "${REGION}" --format=json 2>/dev/null || true)"

get_current_service_env_value() {
  local env_name="$1"

  if [[ -z "${CURRENT_SERVICE_CONFIG_JSON}" ]]; then
    return 0
  fi

  printf '%s' "${CURRENT_SERVICE_CONFIG_JSON}" | jq -r --arg env_name "${env_name}" '
    .spec.template.spec.containers[0].env[]?
    | select(.name == $env_name and has("value"))
    | .value
  ' | head -n 1
}

get_current_service_secret_name() {
  local env_name="$1"

  if [[ -z "${CURRENT_SERVICE_CONFIG_JSON}" ]]; then
    return 0
  fi

  printf '%s' "${CURRENT_SERVICE_CONFIG_JSON}" | jq -r --arg env_name "${env_name}" '
    .spec.template.spec.containers[0].env[]?
    | select(.name == $env_name and has("valueFrom"))
    | .valueFrom.secretKeyRef.secret // ""
  ' | head -n 1
}

DAILY_SPARKS_EDITORIAL_ADMIN_PASSWORD_VALUE="${DAILY_SPARKS_EDITORIAL_ADMIN_PASSWORD:-$(get_current_service_env_value DAILY_SPARKS_EDITORIAL_ADMIN_PASSWORD)}"
DAILY_SPARKS_EDITORIAL_ADMIN_SESSION_SECRET_VALUE="${DAILY_SPARKS_EDITORIAL_ADMIN_SESSION_SECRET:-$(get_current_service_env_value DAILY_SPARKS_EDITORIAL_ADMIN_SESSION_SECRET)}"
DAILY_SPARKS_AI_CONFIG_ENCRYPTION_SECRET_VALUE="${DAILY_SPARKS_AI_CONFIG_ENCRYPTION_SECRET:-$(get_current_service_env_value DAILY_SPARKS_AI_CONFIG_ENCRYPTION_SECRET)}"
NEXT_PUBLIC_GA_MEASUREMENT_ID_VALUE="${NEXT_PUBLIC_GA_MEASUREMENT_ID:-$(get_current_service_env_value NEXT_PUBLIC_GA_MEASUREMENT_ID)}"
DAILY_BRIEF_DELIVERY_MODE_VALUE="${DAILY_BRIEF_DELIVERY_MODE:-$(get_current_service_env_value DAILY_BRIEF_DELIVERY_MODE)}"
DAILY_BRIEF_CANARY_PARENT_EMAILS_VALUE="${DAILY_BRIEF_CANARY_PARENT_EMAILS:-$(get_current_service_env_value DAILY_BRIEF_CANARY_PARENT_EMAILS)}"
DAILY_BRIEF_OPS_ALERT_WEBHOOK_URL_VALUE="${DAILY_BRIEF_OPS_ALERT_WEBHOOK_URL:-$(get_current_service_env_value DAILY_BRIEF_OPS_ALERT_WEBHOOK_URL)}"
DAILY_BRIEF_OPS_ALERT_WEBHOOK_URL_SECRET_VALUE="${DAILY_BRIEF_OPS_ALERT_WEBHOOK_URL_SECRET:-$(get_current_service_secret_name DAILY_BRIEF_OPS_ALERT_WEBHOOK_URL)}"
DAILY_SPARKS_SCHEDULER_SECRET_SECRET_VALUE="${DAILY_SPARKS_SCHEDULER_SECRET_SECRET:-$(get_current_service_secret_name DAILY_SPARKS_SCHEDULER_SECRET)}"

if [[ -n "${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY:-}" ]]; then
  ENV_VARS="${ENV_VARS},NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}"
fi

if [[ -n "${NOTION_OAUTH_CLIENT_ID_VALUE}" ]]; then
  ENV_VARS="${ENV_VARS},NOTION_OAUTH_CLIENT_ID=${NOTION_OAUTH_CLIENT_ID_VALUE}"
fi

if [[ -n "${NOTION_OAUTH_REDIRECT_URI_VALUE}" ]]; then
  ENV_VARS="${ENV_VARS},NOTION_OAUTH_REDIRECT_URI=${NOTION_OAUTH_REDIRECT_URI_VALUE}"
fi

if [[ -n "${NOTION_API_BASE_URL:-}" ]]; then
  ENV_VARS="${ENV_VARS},NOTION_API_BASE_URL=${NOTION_API_BASE_URL}"
fi

if [[ -n "${NOTION_API_VERSION:-}" ]]; then
  ENV_VARS="${ENV_VARS},NOTION_API_VERSION=${NOTION_API_VERSION}"
fi

if [[ -n "${GOODNOTES_FROM_EMAIL_VALUE}" ]]; then
  ENV_VARS="${ENV_VARS},GOODNOTES_FROM_EMAIL=${GOODNOTES_FROM_EMAIL_VALUE}"
fi

if [[ -n "${GOODNOTES_FROM_NAME_VALUE}" ]]; then
  ENV_VARS="${ENV_VARS},GOODNOTES_FROM_NAME=${GOODNOTES_FROM_NAME_VALUE}"
fi

if [[ -n "${DAILY_SPARKS_EDITORIAL_ADMIN_PASSWORD_VALUE}" ]]; then
  ENV_VARS="${ENV_VARS},DAILY_SPARKS_EDITORIAL_ADMIN_PASSWORD=${DAILY_SPARKS_EDITORIAL_ADMIN_PASSWORD_VALUE}"
fi

if [[ -n "${DAILY_SPARKS_EDITORIAL_ADMIN_SESSION_SECRET_VALUE}" ]]; then
  ENV_VARS="${ENV_VARS},DAILY_SPARKS_EDITORIAL_ADMIN_SESSION_SECRET=${DAILY_SPARKS_EDITORIAL_ADMIN_SESSION_SECRET_VALUE}"
fi

if [[ -n "${DAILY_SPARKS_AI_CONFIG_ENCRYPTION_SECRET_VALUE}" ]]; then
  ENV_VARS="${ENV_VARS},DAILY_SPARKS_AI_CONFIG_ENCRYPTION_SECRET=${DAILY_SPARKS_AI_CONFIG_ENCRYPTION_SECRET_VALUE}"
fi

if [[ -n "${NEXT_PUBLIC_GA_MEASUREMENT_ID_VALUE}" ]]; then
  ENV_VARS="${ENV_VARS},NEXT_PUBLIC_GA_MEASUREMENT_ID=${NEXT_PUBLIC_GA_MEASUREMENT_ID_VALUE}"
fi

if [[ -n "${DAILY_BRIEF_DELIVERY_MODE_VALUE}" ]]; then
  ENV_VARS="${ENV_VARS},DAILY_BRIEF_DELIVERY_MODE=${DAILY_BRIEF_DELIVERY_MODE_VALUE}"
fi

if [[ -n "${DAILY_BRIEF_CANARY_PARENT_EMAILS_VALUE}" ]]; then
  ENV_VARS="${ENV_VARS},DAILY_BRIEF_CANARY_PARENT_EMAILS=${DAILY_BRIEF_CANARY_PARENT_EMAILS_VALUE}"
fi

if [[ -n "${DAILY_BRIEF_OPS_ALERT_WEBHOOK_URL_VALUE}" ]] && [[ -z "${DAILY_BRIEF_OPS_ALERT_WEBHOOK_URL_SECRET_VALUE}" ]]; then
  ENV_VARS="${ENV_VARS},DAILY_BRIEF_OPS_ALERT_WEBHOOK_URL=${DAILY_BRIEF_OPS_ALERT_WEBHOOK_URL_VALUE}"
fi

if [[ -n "${DAILY_SPARKS_SCHEDULER_SECRET:-}" ]] && [[ -z "${DAILY_SPARKS_SCHEDULER_SECRET_SECRET_VALUE}" ]]; then
  ENV_VARS="${ENV_VARS},DAILY_SPARKS_SCHEDULER_SECRET=${DAILY_SPARKS_SCHEDULER_SECRET}"
fi

echo "Building image: ${IMAGE}"
gcloud builds submit --tag "${IMAGE}"

echo "Deploying service: ${SERVICE_NAME}"
DEPLOY_ARGS=(
  --image "${IMAGE}"
  --platform managed
  --region "${REGION}"
  --ingress internal-and-cloud-load-balancing
  --allow-unauthenticated
  --no-cpu-throttling
  --timeout 900
  --set-env-vars "${ENV_VARS}"
)

if [[ -n "${STRIPE_SECRET_KEY_SECRET:-}" ]]; then
  DEPLOY_ARGS+=(--update-secrets "STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY_SECRET}:latest")
fi

if [[ -n "${STRIPE_WEBHOOK_SECRET_SECRET:-}" ]]; then
  DEPLOY_ARGS+=(--update-secrets "STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET_SECRET}:latest")
fi

if [[ -n "${NOTION_OAUTH_CLIENT_SECRET_SECRET:-}" ]]; then
  DEPLOY_ARGS+=(--update-secrets "NOTION_OAUTH_CLIENT_SECRET=${NOTION_OAUTH_CLIENT_SECRET_SECRET}:latest")
fi

if [[ -n "${NOTION_TOKEN_ENCRYPTION_SECRET_SECRET:-}" ]]; then
  DEPLOY_ARGS+=(--update-secrets "NOTION_TOKEN_ENCRYPTION_SECRET=${NOTION_TOKEN_ENCRYPTION_SECRET_SECRET}:latest")
fi

if [[ -n "${GOODNOTES_SMTP_URL_SECRET:-}" ]]; then
  DEPLOY_ARGS+=(--update-secrets "GOODNOTES_SMTP_URL=${GOODNOTES_SMTP_URL_SECRET}:latest")
fi

if [[ -n "${DAILY_BRIEF_OPS_ALERT_WEBHOOK_URL_SECRET_VALUE}" ]]; then
  DEPLOY_ARGS+=(--update-secrets "DAILY_BRIEF_OPS_ALERT_WEBHOOK_URL=${DAILY_BRIEF_OPS_ALERT_WEBHOOK_URL_SECRET_VALUE}:latest")
fi

if [[ -n "${DAILY_SPARKS_SCHEDULER_SECRET_SECRET_VALUE}" ]]; then
  DEPLOY_ARGS+=(--update-secrets "DAILY_SPARKS_SCHEDULER_SECRET=${DAILY_SPARKS_SCHEDULER_SECRET_SECRET_VALUE}:latest")
fi

gcloud run deploy "${SERVICE_NAME}" \
  "${DEPLOY_ARGS[@]}"
