#!/usr/bin/env bash
set -euo pipefail

PROJECT_ID="${GOOGLE_CLOUD_PROJECT:-gen-lang-client-0586185740}"
SERVICE_NAME="${SERVICE_NAME:-dailysparks-web}"
REGION="${REGION:-asia-east2}"
REPOSITORY="${REPOSITORY:-cloud-run-source-deploy}"
IMAGE="${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${SERVICE_NAME}:$(git rev-parse --short HEAD)"
ENV_VARS="NODE_ENV=production,DAILY_SPARKS_STORE_BACKEND=firestore,FIREBASE_PROJECT_ID=${PROJECT_ID}"
NOTION_OAUTH_CLIENT_ID_VALUE="${NOTION_OAUTH_CLIENT_ID:-335d872b-594c-8127-8bae-0037c94dabc3}"
NOTION_OAUTH_REDIRECT_URI_VALUE="${NOTION_OAUTH_REDIRECT_URI:-https://dailysparks.geledtech.com/api/notion/callback}"
GOODNOTES_FROM_EMAIL_VALUE="${GOODNOTES_FROM_EMAIL:-info@geledtech.com}"
GOODNOTES_FROM_NAME_VALUE="${GOODNOTES_FROM_NAME:-Growth Education Limited}"

if [[ -n "${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY:-}" ]]; then
  ENV_VARS="${ENV_VARS},NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}"
fi

if [[ -n "${NOTION_OAUTH_CLIENT_ID_VALUE}" ]]; then
  ENV_VARS="${ENV_VARS},NOTION_OAUTH_CLIENT_ID=${NOTION_OAUTH_CLIENT_ID_VALUE}"
fi

if [[ -n "${NOTION_OAUTH_REDIRECT_URI_VALUE}" ]]; then
  ENV_VARS="${ENV_VARS},NOTION_OAUTH_REDIRECT_URI=${NOTION_OAUTH_REDIRECT_URI_VALUE}"
fi

if [[ -n "${NOTION_API_BASE_URL:-}" ]]; then
  ENV_VARS="${ENV_VARS},NOTION_API_BASE_URL=${NOTION_API_BASE_URL}"
fi

if [[ -n "${NOTION_API_VERSION:-}" ]]; then
  ENV_VARS="${ENV_VARS},NOTION_API_VERSION=${NOTION_API_VERSION}"
fi

if [[ -n "${GOODNOTES_FROM_EMAIL_VALUE}" ]]; then
  ENV_VARS="${ENV_VARS},GOODNOTES_FROM_EMAIL=${GOODNOTES_FROM_EMAIL_VALUE}"
fi

if [[ -n "${GOODNOTES_FROM_NAME_VALUE}" ]]; then
  ENV_VARS="${ENV_VARS},GOODNOTES_FROM_NAME=${GOODNOTES_FROM_NAME_VALUE}"
fi

if [[ -n "${DAILY_SPARKS_AI_CONFIG_ENCRYPTION_SECRET:-}" ]]; then
  ENV_VARS="${ENV_VARS},DAILY_SPARKS_AI_CONFIG_ENCRYPTION_SECRET=${DAILY_SPARKS_AI_CONFIG_ENCRYPTION_SECRET}"
fi

echo "Building image: ${IMAGE}"
gcloud builds submit --tag "${IMAGE}"

echo "Deploying service: ${SERVICE_NAME}"
DEPLOY_ARGS=(
  --image "${IMAGE}"
  --platform managed
  --region "${REGION}"
  --ingress internal-and-cloud-load-balancing
  --allow-unauthenticated
  --set-env-vars "${ENV_VARS}"
)

if [[ -n "${STRIPE_SECRET_KEY_SECRET:-}" ]]; then
  DEPLOY_ARGS+=(--update-secrets "STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY_SECRET}:latest")
fi

if [[ -n "${STRIPE_WEBHOOK_SECRET_SECRET:-}" ]]; then
  DEPLOY_ARGS+=(--update-secrets "STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET_SECRET}:latest")
fi

if [[ -n "${NOTION_OAUTH_CLIENT_SECRET_SECRET:-}" ]]; then
  DEPLOY_ARGS+=(--update-secrets "NOTION_OAUTH_CLIENT_SECRET=${NOTION_OAUTH_CLIENT_SECRET_SECRET}:latest")
fi

if [[ -n "${NOTION_TOKEN_ENCRYPTION_SECRET_SECRET:-}" ]]; then
  DEPLOY_ARGS+=(--update-secrets "NOTION_TOKEN_ENCRYPTION_SECRET=${NOTION_TOKEN_ENCRYPTION_SECRET_SECRET}:latest")
fi

if [[ -n "${GOODNOTES_SMTP_URL_SECRET:-}" ]]; then
  DEPLOY_ARGS+=(--update-secrets "GOODNOTES_SMTP_URL=${GOODNOTES_SMTP_URL_SECRET}:latest")
fi

gcloud run deploy "${SERVICE_NAME}" \
  "${DEPLOY_ARGS[@]}"
